### ISSUE TITLE
REST resource naming rules

### ISSUE THREAD

**Issue by BoKna031** [PSW-2020-ORG9/HealthcareIS#104]
We need to establish REST Resource naming rules. For that we will use [these rules](https://restfulapi.net/resource-naming/).
It is necessary to change the current application so that it matches these rules.

**Comment by rammba** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(0) PR Issue: Renaming REST resources](https://trello.com/c/bjVP2lDt/126-0-pr-issue-renaming-rest-resources)
