### ISSUE TITLE
Data structure for Description in MapObject

### ISSUE THREAD

**Issue by BoKna031** [PSW-2020-ORG9/HealthcareIS#107]
Description inside the MapObject contains logic that the string cannot describe so easily. It is necessary to create a data structure that will separate meaningful parts from Description.

**Comment by rammba** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(0) PR Refactor data structure for mapobject description](https://trello.com/c/hqRGLSVf/125-0-pr-refactor-data-structure-for-mapobject-description)
