### ISSUE TITLE
Main web app project shouldn't contain testing related code + Setup Integration testing pipeline

### ISSUE THREAD

**Issue by nikolapantelic-ftn** [PSW-2020-ORG9/HealthcareIS#75]
The web app project contains code needed for integration testing. As much of the testing logic as possible, if not all, should be moved out of the main project. The code bellow is the most evident problem since it contains test data that is strongly bound to the integration tests.
https://github.com/PSW-2020-ORG9/HealthcareIS/blob/a2872fe5af1d2cc9b876363487ffe983dfa842f7/HospitalWebApp/Context/MySqlTestContext.cs#L1-L152

**Comment by nikolapantelic-ftn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[E0.2] Setup integration tests project.](https://trello.com/c/oXRMGCgv/35-e02-setup-integration-tests-project)

**Comment by FmasterofU** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(5) Create pipeline for integration tests execution as part of PR validation](https://trello.com/c/GEmhwLJl/113-5-create-pipeline-for-integration-tests-execution-as-part-of-pr-validation)

**Comment by FmasterofU** [comment]
Since the devops part of integration testing heavily depends on this issue, i'm bringing it all together here.
